### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [cachix/mixpanel-client#8]
```
mixpanel-client           > /tmp/stack-d52bd2407bb1c272/mixpanel-client-0.3.0/src/MixPanel/Types/EngageData.hs:75:7: error:
mixpanel-client           >     • Couldn't match expected type ‘Data.Aeson.Key.Key’
mixpanel-client           >                   with actual type ‘Text’
mixpanel-client           >     • In the first argument of ‘(.=)’, namely
mixpanel-client           >         ‘operationIdentifier operation’
mixpanel-client           >       In the expression:
mixpanel-client           >         operationIdentifier operation .= toJSON operation
mixpanel-client           >       In the first argument of ‘fromList’, namely
mixpanel-client           >         ‘["$token" .= token, "$distinct_id" .= distinctId, "$time" .= time,
mixpanel-client           >           "$ignore_time" .= ignoreTime, ....]’
mixpanel-client           >    |
mixpanel-client           > 75 |     , operationIdentifier operation .= toJSON operation
mixpanel-client           >    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by alaendle** [comment]
So time to crop a new release for hackage? At least if this should get re-enabled on stackage.
